---
# Ansible playbook for a LEMP server.
#
# @author Jeff Geerling (2014).

- hosts: lemp
  gather_facts: yes

  vars_files:
    - vars/main.yml

  roles:
    - geerlingguy.firewall
    - geerlingguy.repo-epel
    - geerlingguy.repo-remi
    - geerlingguy.mysql
    - geerlingguy.nginx
    - geerlingguy.php
